name: PHP Composer

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Plugin Name'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true
      displayname:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Display Name'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true
      description:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'description'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Find and Replace plugin name display
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "display_name_replace"
        replace: ${{github.event.inputs.displayname}}
        regex: false
    - name: Find and Replace discrioption
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "description_replace"
        replace: ${{github.event.inputs.description}}
        regex: false
    - name: run add git
      run: sudo php addgit ${{github.event.inputs.name}}  
    - name: give list
      run: ls -r
    - name: Commit report
      run: |
        rm -f .git/index
        git reset
        git config --global user.name 'tziki-webduck'
        git config --global user.email 'tziki@webduck.co.il'
        git add .
        git commit -m "Automated report"
        git push